# Generated by Django 5.0.7 on 2024-07-26 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('release_year', models.PositiveIntegerField()),
                ('os', models.CharField(max_length=50)),
                ('display_size', models.FloatField()),
                ('ram', models.PositiveIntegerField()),
                ('storage', models.PositiveIntegerField()),
                ('battery_capacity', models.PositiveIntegerField()),
                ('main_camera', models.PositiveIntegerField()),
                ('front_camera', models.PositiveIntegerField()),
                ('previous_price', models.PositiveIntegerField()),
                ('current_price', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='device_images/')),
            ],
        ),
    ]
