# Generated by Django 5.0.7 on 2024-07-26 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='current_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='device',
            name='previous_price',
            field=models.IntegerField(),
        ),
    ]
